spring:
  application:
    name: thesis-api-server
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: 8081

settings:
  files-directory: "/tmp/${spring.application.name}/recognized"
  text-recognizer:
    command: "python /text-recognizer/main.py"
    images-directory: "/tmp/${spring.application.name}/images"
    recognition-timeout-ms: 60000