spring:
  application:
    name: thesis-api-server

server:
  port: 8081

settings:
  files-directory: "/tmp/${spring.application.name}/recognized"
  text-recognizer:
    command: "python /text-recognizer/main.py"
    images-directory: "/tmp/${spring.application.name}/images"
    recognition-timeout-ms: 40000